[project]
name = "agents"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "google-adk>=0.5.0",
    "ipykernel>=6.29.5",
    "pandas>=2.2.3",
    "pypdf2>=3.0.1",
    "ruff>=0.11.9",
]
